-- -----------------------------------------------------
-- Inserção de produtos
-- -----------------------------------------------------
USE `mercato_db`;

-- Primeiro, atualizar os produtos existentes com category_id
UPDATE products p
JOIN product_category pc ON p.category = pc.category_name
SET p.category_id = pc.id;

-- Agora inserir os produtos (apenas se a tabela estiver vazia)
INSERT IGNORE INTO products (name, price, category, category_id, description, image_url, stock, seller_id) VALUES
-- Books (25 produtos)
('Crash Course in Python', 14.99, 'Books', 1, 'Learn Python at your own pace.', 'products/books/book-luv2code-1000.png', 100, 1),
('Become a Guru in JavaScript', 20.99, 'Books', 1, 'Learn JavaScript at your own pace.', 'products/books/book-luv2code-1001.png', 100, 1),
('Exploring Vue.js', 14.99, 'Books', 1, 'Learn Vue.js at your own pace.', 'products/books/book-luv2code-1002.png', 100, 1),
('Advanced Techniques in Big Data', 13.99, 'Books', 1, 'Learn Big Data at your own pace.', 'products/books/book-luv2code-1003.png', 100, 1),
('Crash Course in Big Data', 18.99, 'Books', 1, 'Learn Big Data at your own pace.', 'products/books/book-luv2code-1004.png', 100, 1),
('JavaScript Cookbook', 23.99, 'Books', 1, 'Learn JavaScript at your own pace.', 'products/books/book-luv2code-1005.png', 100, 1),
('Beginners Guide to SQL', 14.99, 'Books', 1, 'Learn SQL at your own pace.', 'products/books/book-luv2code-1006.png', 100, 1),
('Advanced Techniques in JavaScript', 16.99, 'Books', 1, 'Learn JavaScript at your own pace.', 'products/books/book-luv2code-1007.png', 100, 1),
('Introduction to Spring Boot', 25.99, 'Books', 1, 'Learn Spring Boot at your own pace.', 'products/books/book-luv2code-1008.png', 100, 1),
('Become a Guru in React.js', 23.99, 'Books', 1, 'Learn React.js at your own pace.', 'products/books/book-luv2code-1009.png', 100, 1),
('Beginners Guide to Data Science', 24.99, 'Books', 1, 'Learn Data Science at your own pace.', 'products/books/book-luv2code-1010.png', 100, 1),
('Advanced Techniques in Java', 19.99, 'Books', 1, 'Learn Java at your own pace.', 'products/books/book-luv2code-1011.png', 100, 1),
('Exploring DevOps', 24.99, 'Books', 1, 'Learn DevOps at your own pace.', 'products/books/book-luv2code-1012.png', 100, 1),
('The Expert Guide to SQL', 19.99, 'Books', 1, 'Learn SQL at your own pace.', 'products/books/book-luv2code-1013.png', 100, 1),
('Introduction to SQL', 22.99, 'Books', 1, 'Learn SQL at your own pace.', 'products/books/book-luv2code-1014.png', 100, 1),
('The Expert Guide to JavaScript', 22.99, 'Books', 1, 'Learn JavaScript at your own pace.', 'products/books/book-luv2code-1015.png', 100, 1),
('Exploring React.js', 27.99, 'Books', 1, 'Learn React.js at your own pace.', 'products/books/book-luv2code-1016.png', 100, 1),
('Advanced Techniques in React.js', 13.99, 'Books', 1, 'Learn React.js at your own pace.', 'products/books/book-luv2code-1017.png', 100, 1),
('Introduction to C#', 26.99, 'Books', 1, 'Learn C# at your own pace.', 'products/books/book-luv2code-1018.png', 100, 1),
('Crash Course in JavaScript', 13.99, 'Books', 1, 'Learn JavaScript at your own pace.', 'products/books/book-luv2code-1019.png', 100, 1),
('Introduction to Machine Learning', 19.99, 'Books', 1, 'Learn Machine Learning at your own pace.', 'products/books/book-luv2code-1020.png', 100, 1),
('Become a Guru in Java', 18.99, 'Books', 1, 'Learn Java at your own pace.', 'products/books/book-luv2code-1021.png', 100, 1),
('Introduction to Python', 26.99, 'Books', 1, 'Learn Python at your own pace.', 'products/books/book-luv2code-1022.png', 100, 1),
('Advanced Techniques in C#', 22.99, 'Books', 1, 'Learn C# at your own pace.', 'products/books/book-luv2code-1023.png', 100, 1),
('The Expert Guide to Machine Learning', 16.99, 'Books', 1, 'Learn Machine Learning at your own pace.', 'products/books/book-luv2code-1024.png', 100, 1),

-- Coffee Mugs (25 produtos)
('Coffee Mug - Express', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1000.png', 100, 1),
('Coffee Mug - Cherokee', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1001.png', 100, 1),
('Coffee Mug - Sweeper', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1002.png', 100, 1),
('Coffee Mug - Aspire', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1003.png', 100, 1),
('Coffee Mug - Dorian', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1004.png', 100, 1),
('Coffee Mug - Columbia', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1005.png', 100, 1),
('Coffee Mug - Worthing', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1006.png', 100, 1),
('Coffee Mug - Oak Cliff', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1007.png', 100, 1),
('Coffee Mug - Tachyon', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1008.png', 100, 1),
('Coffee Mug - Pan', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1009.png', 100, 1),
('Coffee Mug - Phase', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1010.png', 100, 1),
('Coffee Mug - Falling', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1011.png', 100, 1),
('Coffee Mug - Wispy', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1012.png', 100, 1),
('Coffee Mug - Arlington', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1013.png', 100, 1),
('Coffee Mug - Gazing', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1014.png', 100, 1),
('Coffee Mug - Azura', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1015.png', 100, 1),
('Coffee Mug - Quantum Leap', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1016.png', 100, 1),
('Coffee Mug - Light Years', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1017.png', 100, 1),
('Coffee Mug - Taylor', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1018.png', 100, 1),
('Coffee Mug - Gracia', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1019.png', 100, 1),
('Coffee Mug - Relax', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1020.png', 100, 1),
('Coffee Mug - Windermere', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1021.png', 100, 1),
('Coffee Mug - Prancer', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1022.png', 100, 1),
('Coffee Mug - Recursion', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1023.png', 100, 1),
('Coffee Mug - Treasure', 18.99, 'Coffee Mugs', 2, 'Elegant coffee mug with fractal design.', 'products/coffeemugs/coffeemug-luv2code-1024.png', 100, 1),

-- Mouse Pads (25 produtos)
('Mouse Pad - Express', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1000.png', 100, 1),
('Mouse Pad - Cherokee', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1001.png', 100, 1),
('Mouse Pad - Sweeper', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1002.png', 100, 1),
('Mouse Pad - Aspire', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1003.png', 100, 1),
('Mouse Pad - Dorian', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1004.png', 100, 1),
('Mouse Pad - Columbia', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1005.png', 100, 1),
('Mouse Pad - Worthing', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1006.png', 100, 1),
('Mouse Pad - Oak Cliff', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1007.png', 100, 1),
('Mouse Pad - Tachyon', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1008.png', 100, 1),
('Mouse Pad - Pan', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1009.png', 100, 1),
('Mouse Pad - Phase', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1010.png', 100, 1),
('Mouse Pad - Falling', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1011.png', 100, 1),
('Mouse Pad - Wispy', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1012.png', 100, 1),
('Mouse Pad - Arlington', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1013.png', 100, 1),
('Mouse Pad - Gazing', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1014.png', 100, 1),
('Mouse Pad - Azura', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1015.png', 100, 1),
('Mouse Pad - Quantum Leap', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1016.png', 100, 1),
('Mouse Pad - Light Years', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1017.png', 100, 1),
('Mouse Pad - Taylor', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1018.png', 100, 1),
('Mouse Pad - Gracia', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1019.png', 100, 1),
('Mouse Pad - Relax', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1020.png', 100, 1),
('Mouse Pad - Windermere', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1021.png', 100, 1),
('Mouse Pad - Prancer', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1022.png', 100, 1),
('Mouse Pad - Recursion', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1023.png', 100, 1),
('Mouse Pad - Treasure', 17.99, 'Mouse Pads', 3, 'Mouse pad with unique fractal design.', 'products/mousepads/mousepad-luv2code-1024.png', 100, 1),

-- Luggage Tags (25 produtos)
('Luggage Tag - Cherish', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1000.png', 100, 1),
('Luggage Tag - Adventure', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1001.png', 100, 1),
('Luggage Tag - Skyline', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1002.png', 100, 1),
('Luggage Tag - River', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1003.png', 100, 1),
('Luggage Tag - Trail Steps', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1004.png', 100, 1),
('Luggage Tag - Blooming', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1005.png', 100, 1),
('Luggage Tag - Park', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1006.png', 100, 1),
('Luggage Tag - Beauty', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1007.png', 100, 1),
('Luggage Tag - Water Fall', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1008.png', 100, 1),
('Luggage Tag - Trail', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1009.png', 100, 1),
('Luggage Tag - Skyscraper', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1010.png', 100, 1),
('Luggage Tag - Leaf', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1011.png', 100, 1),
('Luggage Tag - Jungle', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1012.png', 100, 1),
('Luggage Tag - Shoreline', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1013.png', 100, 1),
('Luggage Tag - Blossom', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1014.png', 100, 1),
('Luggage Tag - Lock', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1015.png', 100, 1),
('Luggage Tag - Cafe', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1016.png', 100, 1),
('Luggage Tag - Darling', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1017.png', 100, 1),
('Luggage Tag - Full Stack', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1018.png', 100, 1),
('Luggage Tag - Courtyard', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1019.png', 100, 1),
('Luggage Tag - Coaster', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1020.png', 100, 1),
('Luggage Tag - Bridge', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1021.png', 100, 1),
('Luggage Tag - Sunset', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1022.png', 100, 1),
('Luggage Tag - Flames', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1023.png', 100, 1),
('Luggage Tag - Countryside', 16.99, 'Luggage Tags', 4, 'Unique luggage tag for identification.', 'products/luggagetags/luggagetag-luv2code-1024.png', 100, 1);